SELECT 
      VENDOR_ID, INVOICE_ID, INVOICE_DATE,
      (INVOICE_TOTAL - (PAYMENT_TOTAL + CREDIT_TOTAL)) as balancedue,
      TO_CHAR((INVOICE_TOTAL - (PAYMENT_TOTAL + CREDIT_TOTAL)), '$999999999.99') as balanceR
FROM 
      INVOICES
WHERE 
      (INVOICE_TOTAL - (PAYMENT_TOTAL + CREDIT_TOTAL)) > 1000
ORDER BY
      balancedue desc;
